//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MasterData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MasterData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MasterData", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert !.
        /// </summary>
        internal static string Alert_Header_Alert {
            get {
                return ResourceManager.GetString("Alert_Header_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Alert_Header_Info {
            get {
                return ResourceManager.GetString("Alert_Header_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Listing.
        /// </summary>
        internal static string chMa_Ad_Archive_Text {
            get {
                return ResourceManager.GetString("chMa_Ad_Archive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Management.
        /// </summary>
        internal static string chMa_Ad_GroupManage_Text {
            get {
                return ResourceManager.GetString("chMa_Ad_GroupManage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string chMa_Ad_Search_Text {
            get {
                return ResourceManager.GetString("chMa_Ad_Search_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string chMa_Ad_Usermange_Text {
            get {
                return ResourceManager.GetString("chMa_Ad_Usermange_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Management.
        /// </summary>
        internal static string chMa_Ad_VideoManage_Text {
            get {
                return ResourceManager.GetString("chMa_Ad_VideoManage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string chMa_User_Search_Text {
            get {
                return ResourceManager.GetString("chMa_User_Search_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Management.
        /// </summary>
        internal static string chMa_User_VideoManage_Text {
            get {
                return ResourceManager.GetString("chMa_User_VideoManage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string drp_Configuration_text {
            get {
                return ResourceManager.GetString("drp_Configuration_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string drp_LogOut_Text {
            get {
                return ResourceManager.GetString("drp_LogOut_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to acces this portal, Please contact your administrator.
        /// </summary>
        internal static string Error_Message_Autherization {
            get {
                return ResourceManager.GetString("Error_Message_Autherization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size :.
        /// </summary>
        internal static string Grid_PageSize_Label {
            get {
                return ResourceManager.GetString("Grid_PageSize_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        internal static string hd_Arb_lnk_Text {
            get {
                return ResourceManager.GetString("hd_Arb_lnk_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string hd_Eng_lnk_Text {
            get {
                return ResourceManager.GetString("hd_Eng_lnk_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video on Demand.
        /// </summary>
        internal static string Hd_Title {
            get {
                return ResourceManager.GetString("Hd_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string logedUserWelcome_Text {
            get {
                return ResourceManager.GetString("logedUserWelcome_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_btnSubmit {
            get {
                return ResourceManager.GetString("Login_btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password ?.
        /// </summary>
        internal static string Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Admin Login.
        /// </summary>
        internal static string Login_Hd_SuperAdminLogin {
            get {
                return ResourceManager.GetString("Login_Hd_SuperAdminLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please provide valid username and password..
        /// </summary>
        internal static string Login_lblError_Text {
            get {
                return ResourceManager.GetString("Login_lblError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Sent to provided mail.
        /// </summary>
        internal static string Login_Msg_Email_Sent {
            get {
                return ResourceManager.GetString("Login_Msg_Email_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered User Name not exists.
        /// </summary>
        internal static string Login_Msg_Enter_UserName_NotExists {
            get {
                return ResourceManager.GetString("Login_Msg_Enter_UserName_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed while sending the mail.
        /// </summary>
        internal static string Login_Msg_SendMail_failed {
            get {
                return ResourceManager.GetString("Login_Msg_SendMail_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP details connection failed.
        /// </summary>
        internal static string Login_Msg_SMTP_Connection_Failed {
            get {
                return ResourceManager.GetString("Login_Msg_SMTP_Connection_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string Login_RememeberMe {
            get {
                return ResourceManager.GetString("Login_RememeberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password here.
        /// </summary>
        internal static string Login_txtPwd_PlaceHolder {
            get {
                return ResourceManager.GetString("Login_txtPwd_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Password.
        /// </summary>
        internal static string Login_txtPwd_Req_Error {
            get {
                return ResourceManager.GetString("Login_txtPwd_Req_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter user name here.
        /// </summary>
        internal static string Login_txtUser_PlaceHolder {
            get {
                return ResourceManager.GetString("Login_txtUser_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter UserId.
        /// </summary>
        internal static string Login_txtUser_Req_Error {
            get {
                return ResourceManager.GetString("Login_txtUser_Req_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string mdlLogin_Submit {
            get {
                return ResourceManager.GetString("mdlLogin_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string mdlLog_Hd_forgotPassword {
            get {
                return ResourceManager.GetString("mdlLog_Hd_forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string mdlLoG_UserName {
            get {
                return ResourceManager.GetString("mdlLoG_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter User Name here.
        /// </summary>
        internal static string mdlLog_userName_Placeholder {
            get {
                return ResourceManager.GetString("mdlLog_userName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ResetP_btnSubmit {
            get {
                return ResourceManager.GetString("ResetP_btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Key.
        /// </summary>
        internal static string ResetP_lbl_OneTimeKey_Text {
            get {
                return ResourceManager.GetString("ResetP_lbl_OneTimeKey_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name required.
        /// </summary>
        internal static string ResetP_lbl_UserName_need {
            get {
                return ResourceManager.GetString("ResetP_lbl_UserName_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name :.
        /// </summary>
        internal static string ResetP_lbl_UserName_Text {
            get {
                return ResourceManager.GetString("ResetP_lbl_UserName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset key required.
        /// </summary>
        internal static string ResetP_OneTimeKey_Username_need {
            get {
                return ResourceManager.GetString("ResetP_OneTimeKey_Username_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password :.
        /// </summary>
        internal static string ResetP_Password {
            get {
                return ResourceManager.GetString("ResetP_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required.
        /// </summary>
        internal static string ResetP_Password_need {
            get {
                return ResourceManager.GetString("ResetP_Password_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-type Password :.
        /// </summary>
        internal static string ResetP_Retype_Password {
            get {
                return ResourceManager.GetString("ResetP_Retype_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required.
        /// </summary>
        internal static string ResetP_Retype_Password_need {
            get {
                return ResourceManager.GetString("ResetP_Retype_Password_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter same password .
        /// </summary>
        internal static string ResetP_Retype_Password_Valid {
            get {
                return ResourceManager.GetString("ResetP_Retype_Password_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter reset key sent to the configured super admin mail.
        /// </summary>
        internal static string Reset_Key_SentToMail_Text {
            get {
                return ResourceManager.GetString("Reset_Key_SentToMail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string RESET_mdlAlt_HdText {
            get {
                return ResourceManager.GetString("RESET_mdlAlt_HdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Login.
        /// </summary>
        internal static string reset_mdl_btnRedirect_To_Login {
            get {
                return ResourceManager.GetString("reset_mdl_btnRedirect_To_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string reset_mdl_Cancel {
            get {
                return ResourceManager.GetString("reset_mdl_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please configure the setup correctly before access this portal.
        /// </summary>
        internal static string Setup_Not_Configured {
            get {
                return ResourceManager.GetString("Setup_Not_Configured", resourceCulture);
            }
        }
    }
}
