//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Road {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Road() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Road", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Road details found.
        /// </summary>
        internal static string gvRoad_EmptyData_Text {
            get {
                return ResourceManager.GetString("gvRoad_EmptyData_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIONS.
        /// </summary>
        internal static string gvRoad_Hd_Actions {
            get {
                return ResourceManager.GetString("gvRoad_Hd_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROAD NAME.
        /// </summary>
        internal static string gvRoad_Head_RoadName {
            get {
                return ResourceManager.GetString("gvRoad_Head_RoadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road.
        /// </summary>
        internal static string Head_Road {
            get {
                return ResourceManager.GetString("Head_Road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Road.
        /// </summary>
        internal static string lnk_Create_Road_text {
            get {
                return ResourceManager.GetString("lnk_Create_Road_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Road.
        /// </summary>
        internal static string lnk_Import_Road {
            get {
                return ResourceManager.GetString("lnk_Import_Road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert !.
        /// </summary>
        internal static string mdlAlrt_Head {
            get {
                return ResourceManager.GetString("mdlAlrt_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string mdlAlrt_Ok {
            get {
                return ResourceManager.GetString("mdlAlrt_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import From Excel.
        /// </summary>
        internal static string mdlBtnImport {
            get {
                return ResourceManager.GetString("mdlBtnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mdlCR_Cancel {
            get {
                return ResourceManager.GetString("mdlCR_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Road.
        /// </summary>
        internal static string mdlCR_Head_CretRoad {
            get {
                return ResourceManager.GetString("mdlCR_Head_CretRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Name :.
        /// </summary>
        internal static string mdlCR_Road_Name_label {
            get {
                return ResourceManager.GetString("mdlCR_Road_Name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter road name here...
        /// </summary>
        internal static string mdlCR_Road_Name_placeHolder {
            get {
                return ResourceManager.GetString("mdlCR_Road_Name_placeHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Number.
        /// </summary>
        internal static string mdlCR_Road_Number_label {
            get {
                return ResourceManager.GetString("mdlCR_Road_Number_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter road number here.
        /// </summary>
        internal static string mdlCR_Road_Number_placeHolder {
            get {
                return ResourceManager.GetString("mdlCR_Road_Number_placeHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string mdlCR_Save {
            get {
                return ResourceManager.GetString("mdlCR_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mdlDel_Cancel {
            get {
                return ResourceManager.GetString("mdlDel_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are&amp;nbsp;you&amp;nbsp;sure&amp;nbsp;to&amp;nbsp;delete&amp;nbsp;road.
        /// </summary>
        internal static string mdlDel_DelConfim_Text {
            get {
                return ResourceManager.GetString("mdlDel_DelConfim_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string mdlDel_Delete {
            get {
                return ResourceManager.GetString("mdlDel_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Warning.
        /// </summary>
        internal static string mdlDel_DelWarning {
            get {
                return ResourceManager.GetString("mdlDel_DelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing Roads .
        /// </summary>
        internal static string mdlImport_Confm_Header {
            get {
                return ResourceManager.GetString("mdlImport_Confm_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mdlUR_Cancel {
            get {
                return ResourceManager.GetString("mdlUR_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Road.
        /// </summary>
        internal static string mdlUR_Head_Road {
            get {
                return ResourceManager.GetString("mdlUR_Head_Road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Name :.
        /// </summary>
        internal static string mdlUR_Road_Name_label {
            get {
                return ResourceManager.GetString("mdlUR_Road_Name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter road name here...
        /// </summary>
        internal static string mdlUR_Road_Name_Placeholder {
            get {
                return ResourceManager.GetString("mdlUR_Road_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string mdlUR_Save {
            get {
                return ResourceManager.GetString("mdlUR_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Importing Road from Excel,Data Columns order should be like RoadNo,Arbic Road Name and English Road Name.
        /// </summary>
        internal static string MSG_Excel_Import_Format {
            get {
                return ResourceManager.GetString("MSG_Excel_Import_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road not deleted,as it is assigned to another.
        /// </summary>
        internal static string MSG_ROAD_Delete_Failed {
            get {
                return ResourceManager.GetString("MSG_ROAD_Delete_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road deleted successfully.
        /// </summary>
        internal static string MSG_ROAD_DELETE_SUCESS {
            get {
                return ResourceManager.GetString("MSG_ROAD_DELETE_SUCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roads importing failed.
        /// </summary>
        internal static string MSG_Road_Import_Failed {
            get {
                return ResourceManager.GetString("MSG_Road_Import_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of {0} roads {1} roads imported.
        /// </summary>
        internal static string MSG_Road_Import_SucessFor {
            get {
                return ResourceManager.GetString("MSG_Road_Import_SucessFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road not saved ,enter valid road number.
        /// </summary>
        internal static string MSG_Road_Save_Failed {
            get {
                return ResourceManager.GetString("MSG_Road_Save_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Number already exists.
        /// </summary>
        internal static string MSG_Road_Save_Failed_RoadNo_Exists {
            get {
                return ResourceManager.GetString("MSG_Road_Save_Failed_RoadNo_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road saved successfully.
        /// </summary>
        internal static string MSG_ROAD_SAVE_Sucess {
            get {
                return ResourceManager.GetString("MSG_ROAD_SAVE_Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road updated successfully.
        /// </summary>
        internal static string MSG_Road_Upadate_Sucess {
            get {
                return ResourceManager.GetString("MSG_Road_Upadate_Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Select the excel file to import.
        /// </summary>
        internal static string MSG_Select_Excel_Import {
            get {
                return ResourceManager.GetString("MSG_Select_Excel_Import", resourceCulture);
            }
        }
    }
}
