//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Search {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Search() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Search", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tag.
        /// </summary>
        internal static string AlertMsgModal_Header {
            get {
                return ResourceManager.GetString("AlertMsgModal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ALM_btnOK_Text {
            get {
                return ResourceManager.GetString("ALM_btnOK_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnsearch_text {
            get {
                return ResourceManager.GetString("btnsearch_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ddlSearchOn_dropdown {
            get {
                return ResourceManager.GetString("ddlSearchOn_dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string gvSearch_gridview {
            get {
                return ResourceManager.GetString("gvSearch_gridview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No videos assigned to you.
        /// </summary>
        internal static string gv_EmptyData_NoGroupsAssinged {
            get {
                return ResourceManager.GetString("gv_EmptyData_NoGroupsAssinged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search results to display..
        /// </summary>
        internal static string gv_EmtpyData {
            get {
                return ResourceManager.GetString("gv_EmtpyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Name.
        /// </summary>
        internal static string gv_Hd_VideoName {
            get {
                return ResourceManager.GetString("gv_Hd_VideoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string GV_TAG_headertext {
            get {
                return ResourceManager.GetString("GV_TAG_headertext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one filter tag.
        /// </summary>
        internal static string MSG_Select_Atleast_OneTag {
            get {
                return ResourceManager.GetString("MSG_Select_Atleast_OneTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search keywords...
        /// </summary>
        internal static string txtSearch_PlaceHolder {
            get {
                return ResourceManager.GetString("txtSearch_PlaceHolder", resourceCulture);
            }
        }
    }
}
