//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Setup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Setup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Setup", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string ADD_Fot_btnNext {
            get {
                return ResourceManager.GetString("ADD_Fot_btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are not sure about database details, please contact your host..
        /// </summary>
        internal static string ADD_Fot_DbDetailsSureMessage {
            get {
                return ResourceManager.GetString("ADD_Fot_DbDetailsSureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates mandatory fields.
        /// </summary>
        internal static string ADD_Fot_IndicatesMadatory {
            get {
                return ResourceManager.GetString("ADD_Fot_IndicatesMadatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter active directory access details..
        /// </summary>
        internal static string ADD_Hd_enter_AD_Details {
            get {
                return ResourceManager.GetString("ADD_Hd_enter_AD_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Name.
        /// </summary>
        internal static string ADD_lbl_DomainName {
            get {
                return ResourceManager.GetString("ADD_lbl_DomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string ADD_lbl_Password {
            get {
                return ResourceManager.GetString("ADD_lbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server ID.
        /// </summary>
        internal static string ADD_lbl_ServerAddress {
            get {
                return ResourceManager.GetString("ADD_lbl_ServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string ADD_lbl_UserName {
            get {
                return ResourceManager.GetString("ADD_lbl_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Password.
        /// </summary>
        internal static string ADD_REqu_Password {
            get {
                return ResourceManager.GetString("ADD_REqu_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Username.
        /// </summary>
        internal static string ADD_REQu_UserName {
            get {
                return ResourceManager.GetString("ADD_REQu_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Domain Name.
        /// </summary>
        internal static string ADD_Req_DomainName {
            get {
                return ResourceManager.GetString("ADD_Req_DomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter ServerID.
        /// </summary>
        internal static string ADD_Req_ServerId {
            get {
                return ResourceManager.GetString("ADD_Req_ServerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database already exists.
        /// </summary>
        internal static string DBS_Connection_Already_Exists {
            get {
                return ResourceManager.GetString("DBS_Connection_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database not created failed.
        /// </summary>
        internal static string DBS_Database_CreationFailed {
            get {
                return ResourceManager.GetString("DBS_Database_CreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With provided details the connection not established. Please provide valid details..
        /// </summary>
        internal static string DBS_DBConnection_NotEstbl_Message {
            get {
                return ResourceManager.GetString("DBS_DBConnection_NotEstbl_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string DBS_Fot_btnNext {
            get {
                return ResourceManager.GetString("DBS_Fot_btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are not sure about database details, please contact your host..
        /// </summary>
        internal static string DBS_Fot_DbDetailsSureMessage {
            get {
                return ResourceManager.GetString("DBS_Fot_DbDetailsSureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates mandatory fields.
        /// </summary>
        internal static string DBS_Fot_IndicatesMadatory {
            get {
                return ResourceManager.GetString("DBS_Fot_IndicatesMadatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter database connection details.
        /// </summary>
        internal static string DBS_Hd_enterDBDetails {
            get {
                return ResourceManager.GetString("DBS_Hd_enterDBDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name.
        /// </summary>
        internal static string DBS_lbl_DBName {
            get {
                return ResourceManager.GetString("DBS_lbl_DBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string DBS_lbl_IPAddress {
            get {
                return ResourceManager.GetString("DBS_lbl_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string DBS_lbl_Password {
            get {
                return ResourceManager.GetString("DBS_lbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string DBS_lbl_Port {
            get {
                return ResourceManager.GetString("DBS_lbl_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string DBS_lbl_UserID {
            get {
                return ResourceManager.GetString("DBS_lbl_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert !.
        /// </summary>
        internal static string DBS_mdlAlt_HdText {
            get {
                return ResourceManager.GetString("DBS_mdlAlt_HdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string DBS_mdlAlt_Ok {
            get {
                return ResourceManager.GetString("DBS_mdlAlt_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database already exists.
        /// </summary>
        internal static string DBS_MSG_DBExists {
            get {
                return ResourceManager.GetString("DBS_MSG_DBExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login already exists.
        /// </summary>
        internal static string DBS_MSG_LoginAlreadyExists {
            get {
                return ResourceManager.GetString("DBS_MSG_LoginAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishing connection failed,Provide valid connection details..
        /// </summary>
        internal static string DBS_MSG_Provide_Valid_Connection {
            get {
                return ResourceManager.GetString("DBS_MSG_Provide_Valid_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Database.
        /// </summary>
        internal static string DBS_REq_DBName {
            get {
                return ResourceManager.GetString("DBS_REq_DBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter IP Address.
        /// </summary>
        internal static string DBS_Req_IPAddress {
            get {
                return ResourceManager.GetString("DBS_Req_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Port.
        /// </summary>
        internal static string DBS_Req_PORT {
            get {
                return ResourceManager.GetString("DBS_Req_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Password.
        /// </summary>
        internal static string DBS_Req_PWD {
            get {
                return ResourceManager.GetString("DBS_Req_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter UserId.
        /// </summary>
        internal static string DBS_Req_UserId {
            get {
                return ResourceManager.GetString("DBS_Req_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Valid Database Name.
        /// </summary>
        internal static string DBS_Valid_DatabaseName {
            get {
                return ResourceManager.GetString("DBS_Valid_DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Invalid Ip Address.
        /// </summary>
        internal static string DBS_Valid_IPAddress {
            get {
                return ResourceManager.GetString("DBS_Valid_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Invalid Port.
        /// </summary>
        internal static string DBS_Valid_Port {
            get {
                return ResourceManager.GetString("DBS_Valid_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Setup.
        /// </summary>
        internal static string HD_Step1_DatabaseSetup {
            get {
                return ResourceManager.GetString("HD_Step1_DatabaseSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string HD_Step1_Number {
            get {
                return ResourceManager.GetString("HD_Step1_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string HD_Step2_Number {
            get {
                return ResourceManager.GetString("HD_Step2_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Details.
        /// </summary>
        internal static string HD_Step2_SMTP_Details {
            get {
                return ResourceManager.GetString("HD_Step2_SMTP_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory Details.
        /// </summary>
        internal static string HD_Step3_Active_Directory_Details {
            get {
                return ResourceManager.GetString("HD_Step3_Active_Directory_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string HD_Step3_Number {
            get {
                return ResourceManager.GetString("HD_Step3_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string HD_Step4_Number {
            get {
                return ResourceManager.GetString("HD_Step4_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOD Configuration Details.
        /// </summary>
        internal static string HD_Step4_VOD_Configuration_Details {
            get {
                return ResourceManager.GetString("HD_Step4_VOD_Configuration_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string HD_Step5_Number {
            get {
                return ResourceManager.GetString("HD_Step5_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Admin Info.
        /// </summary>
        internal static string HD_Step5_Super_Admin_Info {
            get {
                return ResourceManager.GetString("HD_Step5_Super_Admin_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is valid.
        /// </summary>
        internal static string MSG_DBS_ConnectionValid {
            get {
                return ResourceManager.GetString("MSG_DBS_ConnectionValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed for the default User.
        /// </summary>
        internal static string MSG_DBS_LoginFailed_DefaultDB {
            get {
                return ResourceManager.GetString("MSG_DBS_LoginFailed_DefaultDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Server was not found or not accessible.
        /// </summary>
        internal static string MSG_DBS_ServerNotFound {
            get {
                return ResourceManager.GetString("MSG_DBS_ServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are not sure about database details, please contact your host..
        /// </summary>
        internal static string SAD_Fot_DbDetailsSureMessage {
            get {
                return ResourceManager.GetString("SAD_Fot_DbDetailsSureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates mandatory fields.
        /// </summary>
        internal static string SAD_Fot_IndicatesMadatory {
            get {
                return ResourceManager.GetString("SAD_Fot_IndicatesMadatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string SAD_Fot_Nextbtn {
            get {
                return ResourceManager.GetString("SAD_Fot_Nextbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Admin Details.
        /// </summary>
        internal static string SAD_Hd_AdminDetails {
            get {
                return ResourceManager.GetString("SAD_Hd_AdminDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string SAD_lbl_Eamil {
            get {
                return ResourceManager.GetString("SAD_lbl_Eamil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SAD_lbl_PWD {
            get {
                return ResourceManager.GetString("SAD_lbl_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-type Password.
        /// </summary>
        internal static string SAD_lbl_REtypePWD {
            get {
                return ResourceManager.GetString("SAD_lbl_REtypePWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string SAD_lbl_UserName {
            get {
                return ResourceManager.GetString("SAD_lbl_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Email.
        /// </summary>
        internal static string SAD_Requ_Eamil {
            get {
                return ResourceManager.GetString("SAD_Requ_Eamil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Password.
        /// </summary>
        internal static string SAD_REqu_PWD {
            get {
                return ResourceManager.GetString("SAD_REqu_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Password.
        /// </summary>
        internal static string SAD_REq_REtypePWD {
            get {
                return ResourceManager.GetString("SAD_REq_REtypePWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Username.
        /// </summary>
        internal static string SAD_Req_Username {
            get {
                return ResourceManager.GetString("SAD_Req_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Invalid Email Address.
        /// </summary>
        internal static string SAD_Valid_Eamil {
            get {
                return ResourceManager.GetString("SAD_Valid_Eamil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Password Doesn&apos;t Match.
        /// </summary>
        internal static string SAD_Valid_REtypePWD {
            get {
                return ResourceManager.GetString("SAD_Valid_REtypePWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string SMTP_btnNext {
            get {
                return ResourceManager.GetString("SMTP_btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        internal static string SMTP_btnTest {
            get {
                return ResourceManager.GetString("SMTP_btnTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Email Type.
        /// </summary>
        internal static string SMTP_EmailType_Need {
            get {
                return ResourceManager.GetString("SMTP_EmailType_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter  Encrypted Connection.
        /// </summary>
        internal static string SMTP_EncryptedConnection_Need {
            get {
                return ResourceManager.GetString("SMTP_EncryptedConnection_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates mandatory fields.
        /// </summary>
        internal static string SMTP_lblMandatoryFields {
            get {
                return ResourceManager.GetString("SMTP_lblMandatoryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are not sure about database details, please contact your host..
        /// </summary>
        internal static string SMTP_lblMessage {
            get {
                return ResourceManager.GetString("SMTP_lblMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Type.
        /// </summary>
        internal static string SMTP_lbl_EmailType {
            get {
                return ResourceManager.GetString("SMTP_lbl_EmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Encrypted Connection.
        /// </summary>
        internal static string SMTP_lbl_EncryptedConnection {
            get {
                return ResourceManager.GetString("SMTP_lbl_EncryptedConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SMTP_lbl_Password {
            get {
                return ResourceManager.GetString("SMTP_lbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string SMTP_lbl_Port {
            get {
                return ResourceManager.GetString("SMTP_lbl_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply To Email.
        /// </summary>
        internal static string SMTP_lbl_ReplyToEmail {
            get {
                return ResourceManager.GetString("SMTP_lbl_ReplyToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Name.
        /// </summary>
        internal static string SMTP_lbl_SenderName {
            get {
                return ResourceManager.GetString("SMTP_lbl_SenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Server.
        /// </summary>
        internal static string SMTP_lbl_ServerId {
            get {
                return ResourceManager.GetString("SMTP_lbl_ServerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter SMTP Details.
        /// </summary>
        internal static string SMTP_lbl_SMTPDetails {
            get {
                return ResourceManager.GetString("SMTP_lbl_SMTPDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Of Encrypted Connection.
        /// </summary>
        internal static string SMTP_lbl_TypeofEncrypt {
            get {
                return ResourceManager.GetString("SMTP_lbl_TypeofEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string SMTP_lbl_Username {
            get {
                return ResourceManager.GetString("SMTP_lbl_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to establish a connection.
        /// </summary>
        internal static string SMTP_MSG_Connection_Failed {
            get {
                return ResourceManager.GetString("SMTP_MSG_Connection_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection established successfully.
        /// </summary>
        internal static string SMTP_MSG_Connection_Sucess {
            get {
                return ResourceManager.GetString("SMTP_MSG_Connection_Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP details saving failed.
        /// </summary>
        internal static string SMTP_MSG_Details_Save_Failed {
            get {
                return ResourceManager.GetString("SMTP_MSG_Details_Save_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP details saved successfully.
        /// </summary>
        internal static string SMTP_MSG_Details_Save_Sucess {
            get {
                return ResourceManager.GetString("SMTP_MSG_Details_Save_Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string SMTP_None_Text {
            get {
                return ResourceManager.GetString("SMTP_None_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string SMTP_None_Value {
            get {
                return ResourceManager.GetString("SMTP_None_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Password.
        /// </summary>
        internal static string SMTP_Password_Need {
            get {
                return ResourceManager.GetString("SMTP_Password_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Port.
        /// </summary>
        internal static string SMTP_Port_Need {
            get {
                return ResourceManager.GetString("SMTP_Port_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Reply To Email.
        /// </summary>
        internal static string SMTP_ReplyToEmail_Need {
            get {
                return ResourceManager.GetString("SMTP_ReplyToEmail_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Sender Name.
        /// </summary>
        internal static string SMTP_SenderName_Need {
            get {
                return ResourceManager.GetString("SMTP_SenderName_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Server Id.
        /// </summary>
        internal static string SMTP_ServerId_Need {
            get {
                return ResourceManager.GetString("SMTP_ServerId_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Invalid Server Id.
        /// </summary>
        internal static string SMTP_ServerId_Valid {
            get {
                return ResourceManager.GetString("SMTP_ServerId_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL.
        /// </summary>
        internal static string SMTP_SSLEnabled_Text {
            get {
                return ResourceManager.GetString("SMTP_SSLEnabled_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLS.
        /// </summary>
        internal static string SMTP_TLSEnabled_Text {
            get {
                return ResourceManager.GetString("SMTP_TLSEnabled_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Select Encrypted Connection.
        /// </summary>
        internal static string SMTP_TypeofEncrypt_Need {
            get {
                return ResourceManager.GetString("SMTP_TypeofEncrypt_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Username.
        /// </summary>
        internal static string SMTP_Username_Need {
            get {
                return ResourceManager.GetString("SMTP_Username_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Enter Valid Archive Folder Path.
        /// </summary>
        internal static string VOD_aRchiveFold_Valid {
            get {
                return ResourceManager.GetString("VOD_aRchiveFold_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Enter Valid Backup Folder Path.
        /// </summary>
        internal static string VOD_BackupFolder_Valid {
            get {
                return ResourceManager.GetString("VOD_BackupFolder_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Enter Valid Destination Folder Path.
        /// </summary>
        internal static string VOD_DestinationFold_Valid {
            get {
                return ResourceManager.GetString("VOD_DestinationFold_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are not sure about database details, please contact your host..
        /// </summary>
        internal static string VOD_Fot_DbDetailsSureMessage {
            get {
                return ResourceManager.GetString("VOD_Fot_DbDetailsSureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates mandatory fields.
        /// </summary>
        internal static string VOD_Fot_IndicatesMadatory {
            get {
                return ResourceManager.GetString("VOD_Fot_IndicatesMadatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string VOD_Fot_NExtBtn {
            get {
                return ResourceManager.GetString("VOD_Fot_NExtBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOD Configuration Details.
        /// </summary>
        internal static string VOD_Hd_VODDetails {
            get {
                return ResourceManager.GetString("VOD_Hd_VODDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Enter Either Interval or Time.
        /// </summary>
        internal static string VOD_IntervalOrTime_Valid {
            get {
                return ResourceManager.GetString("VOD_IntervalOrTime_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Folder.
        /// </summary>
        internal static string VOD_lbl_ArchiveFold {
            get {
                return ResourceManager.GetString("VOD_lbl_ArchiveFold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Folder.
        /// </summary>
        internal static string VOD_lbl_BackupFolder {
            get {
                return ResourceManager.GetString("VOD_lbl_BackupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Folder.
        /// </summary>
        internal static string VOD_lbl_DestinationFold {
            get {
                return ResourceManager.GetString("VOD_lbl_DestinationFold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Interval / Time.
        /// </summary>
        internal static string VOD_lbl_ScheduleInterval {
            get {
                return ResourceManager.GetString("VOD_lbl_ScheduleInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Or) Time.
        /// </summary>
        internal static string VOD_lbl_ScheduleTime {
            get {
                return ResourceManager.GetString("VOD_lbl_ScheduleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simultaneous Video Conversions.
        /// </summary>
        internal static string VOD_lbl_Simul_VideoConversion {
            get {
                return ResourceManager.GetString("VOD_lbl_Simul_VideoConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Folder.
        /// </summary>
        internal static string VOD_lbl_SourceFold {
            get {
                return ResourceManager.GetString("VOD_lbl_SourceFold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Source Folder.
        /// </summary>
        internal static string VOD_REQu_SourceFold {
            get {
                return ResourceManager.GetString("VOD_REQu_SourceFold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Archive Folder.
        /// </summary>
        internal static string VOD_REq_aRchiveFold {
            get {
                return ResourceManager.GetString("VOD_REq_aRchiveFold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Backup Folder.
        /// </summary>
        internal static string VOD_Req_BackupFolder {
            get {
                return ResourceManager.GetString("VOD_Req_BackupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Destination Folder.
        /// </summary>
        internal static string VOD_REq_DestinationFold {
            get {
                return ResourceManager.GetString("VOD_REq_DestinationFold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Select Video Conversion.
        /// </summary>
        internal static string VOD_Req_Simul_VideoConversion {
            get {
                return ResourceManager.GetString("VOD_Req_Simul_VideoConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Enter Valid Source Folder Path.
        /// </summary>
        internal static string VOD_SourceFold_Valid {
            get {
                return ResourceManager.GetString("VOD_SourceFold_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Enter Valid Time (HH:MM) format.
        /// </summary>
        internal static string VOD_Time_Valid {
            get {
                return ResourceManager.GetString("VOD_Time_Valid", resourceCulture);
            }
        }
    }
}
