//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Users {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Users() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Users", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Groups .
        /// </summary>
        internal static string ddlGroupsList_NoGroup_Text {
            get {
                return ResourceManager.GetString("ddlGroupsList_NoGroup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Group.
        /// </summary>
        internal static string ddlGroupsList_SelectGroup_Text {
            get {
                return ResourceManager.GetString("ddlGroupsList_SelectGroup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Domain.
        /// </summary>
        internal static string ddlListBasedOnFilterBy_Select_Domain_Text {
            get {
                return ResourceManager.GetString("ddlListBasedOnFilterBy_Select_Domain_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users to display in selected group.
        /// </summary>
        internal static string gv_EmtpyData {
            get {
                return ResourceManager.GetString("gv_EmtpyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string gv_hd_Actions {
            get {
                return ResourceManager.GetString("gv_hd_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        internal static string gv_hd_Domain {
            get {
                return ResourceManager.GetString("gv_hd_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string gv_hd_fullname {
            get {
                return ResourceManager.GetString("gv_hd_fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        internal static string gv_hd_groupName {
            get {
                return ResourceManager.GetString("gv_hd_groupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active ?.
        /// </summary>
        internal static string gv_hd_IsActive {
            get {
                return ResourceManager.GetString("gv_hd_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string gv_hd_Username {
            get {
                return ResourceManager.GetString("gv_hd_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string hd_UserManagement {
            get {
                return ResourceManager.GetString("hd_UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Color.
        /// </summary>
        internal static string hndRowBackColor_hiddenfield {
            get {
                return ResourceManager.GetString("hndRowBackColor_hiddenfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By.
        /// </summary>
        internal static string lblFilterBy {
            get {
                return ResourceManager.GetString("lblFilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Users.
        /// </summary>
        internal static string lnkActivateUser {
            get {
                return ResourceManager.GetString("lnkActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign To Group.
        /// </summary>
        internal static string lnkAssignUserstoGroup {
            get {
                return ResourceManager.GetString("lnkAssignUserstoGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate Users.
        /// </summary>
        internal static string lnkDeactivateUser {
            get {
                return ResourceManager.GetString("lnkDeactivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Group.
        /// </summary>
        internal static string lnkRemoveUsersFromGroup {
            get {
                return ResourceManager.GetString("lnkRemoveUsersFromGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        internal static string mdlAG_Assign {
            get {
                return ResourceManager.GetString("mdlAG_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Users To Group.
        /// </summary>
        internal static string mdlAG_AssingUsers {
            get {
                return ResourceManager.GetString("mdlAG_AssingUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string mdlAG_btn_Remove {
            get {
                return ResourceManager.GetString("mdlAG_btn_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mdlAG_Cancel {
            get {
                return ResourceManager.GetString("mdlAG_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Group.
        /// </summary>
        internal static string mdlAG_SelectGrp {
            get {
                return ResourceManager.GetString("mdlAG_SelectGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert !.
        /// </summary>
        internal static string mdlAlt_Head {
            get {
                return ResourceManager.GetString("mdlAlt_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string mdlAlt_Ok {
            get {
                return ResourceManager.GetString("mdlAlt_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Action.
        /// </summary>
        internal static string mdlAU_ActionOnUser {
            get {
                return ResourceManager.GetString("mdlAU_ActionOnUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string mdlAU_ActivateUser {
            get {
                return ResourceManager.GetString("mdlAU_ActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mdlAU_CancelButton {
            get {
                return ResourceManager.GetString("mdlAU_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        internal static string mdlAU_DeactivateUser {
            get {
                return ResourceManager.GetString("mdlAU_DeactivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string mdlDel_Delete {
            get {
                return ResourceManager.GetString("mdlDel_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mdlDel_Delete_Cancel {
            get {
                return ResourceManager.GetString("mdlDel_Delete_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete user from group &lt;strong&gt;{0} &lt;/strong&gt; ?.
        /// </summary>
        internal static string mdlDel_DelWarText {
            get {
                return ResourceManager.GetString("mdlDel_DelWarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Warning.
        /// </summary>
        internal static string mdlDel_Header {
            get {
                return ResourceManager.GetString("mdlDel_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        internal static string mdlEUP_Assign {
            get {
                return ResourceManager.GetString("mdlEUP_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mdlEUP_Cancel {
            get {
                return ResourceManager.GetString("mdlEUP_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify User Group.
        /// </summary>
        internal static string mdlEUP_ModfyGroup {
            get {
                return ResourceManager.GetString("mdlEUP_ModfyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Group.
        /// </summary>
        internal static string mdlEUP_SelectGroup {
            get {
                return ResourceManager.GetString("mdlEUP_SelectGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string mdlEUP_UserName {
            get {
                return ResourceManager.GetString("mdlEUP_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Users From Group.
        /// </summary>
        internal static string mdl_Remove_Users_Header {
            get {
                return ResourceManager.GetString("mdl_Remove_Users_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to activate total user(s) .
        /// </summary>
        internal static string MSG_ActiveUser_Confirmation {
            get {
                return ResourceManager.GetString("MSG_ActiveUser_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to activate user.
        /// </summary>
        internal static string MSG_ActiveUser_Confirmation_SingleUser {
            get {
                return ResourceManager.GetString("MSG_ActiveUser_Confirmation_SingleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to deactivate total user(s).
        /// </summary>
        internal static string MSG_DeActivateUser_Confirmation {
            get {
                return ResourceManager.GetString("MSG_DeActivateUser_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to deactivate user.
        /// </summary>
        internal static string MSG_DeActivateUser_Confirmation_SingleUser {
            get {
                return ResourceManager.GetString("MSG_DeActivateUser_Confirmation_SingleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group deleted successfully.
        /// </summary>
        internal static string MSG_Group_Delete_Sucess {
            get {
                return ResourceManager.GetString("MSG_Group_Delete_Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group updated successfully.
        /// </summary>
        internal static string MSG_Group_Updated_Sucess {
            get {
                return ResourceManager.GetString("MSG_Group_Updated_Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No groups assigned to selected users.
        /// </summary>
        internal static string MSG_NoGroups_To_RemoveAssigned {
            get {
                return ResourceManager.GetString("MSG_NoGroups_To_RemoveAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one user to activate.
        /// </summary>
        internal static string MSG_SelectAtleastOne_Activate {
            get {
                return ResourceManager.GetString("MSG_SelectAtleastOne_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one user to assign to group.
        /// </summary>
        internal static string MSG_SelectAtleastOne_Assign {
            get {
                return ResourceManager.GetString("MSG_SelectAtleastOne_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one user to deactivate.
        /// </summary>
        internal static string MSG_SelectAtleastOne_Deactivate {
            get {
                return ResourceManager.GetString("MSG_SelectAtleastOne_Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one user to remove from group.
        /// </summary>
        internal static string MSG_SelectAtleastOne_ToRemoveGroup {
            get {
                return ResourceManager.GetString("MSG_SelectAtleastOne_ToRemoveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected user(s) already in active state.
        /// </summary>
        internal static string MSG_SelectedUser_Already_Active {
            get {
                return ResourceManager.GetString("MSG_SelectedUser_Already_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected User(s) already in deactive state.
        /// </summary>
        internal static string MSG_SelectedUser_Already_DeActive {
            get {
                return ResourceManager.GetString("MSG_SelectedUser_Already_DeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select valid group name.
        /// </summary>
        internal static string MSG_Select_ValidGroupName {
            get {
                return ResourceManager.GetString("MSG_Select_ValidGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User(s) successfully  assigned to group.
        /// </summary>
        internal static string MSG_UserAssined_ToGroup_Sucess {
            get {
                return ResourceManager.GetString("MSG_UserAssined_ToGroup_Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User(s) successfully  removed from group .
        /// </summary>
        internal static string MSG_UserRemovedFrom_Group_Sucess {
            get {
                return ResourceManager.GetString("MSG_UserRemovedFrom_Group_Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User(s) activated successfully.
        /// </summary>
        internal static string MSG_Users_ActivatedSucessfully {
            get {
                return ResourceManager.GetString("MSG_Users_ActivatedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User(s) activation failed.
        /// </summary>
        internal static string MSG_Users_Activation_failed {
            get {
                return ResourceManager.GetString("MSG_Users_Activation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User(s) deactivated successfully.
        /// </summary>
        internal static string MSG_Users_DeActivatedSucessfully {
            get {
                return ResourceManager.GetString("MSG_Users_DeActivatedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User(s) deactivation failed.
        /// </summary>
        internal static string MSG_Users_DeActivation_failed {
            get {
                return ResourceManager.GetString("MSG_Users_DeActivation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing users from group failed.
        /// </summary>
        internal static string MSG_Users_RemovedFromGroup_failed {
            get {
                return ResourceManager.GetString("MSG_Users_RemovedFromGroup_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive users can not be assign to a group.
        /// </summary>
        internal static string MSG_User_Inactive_wouldnot_Assign_Group {
            get {
                return ResourceManager.GetString("MSG_User_Inactive_wouldnot_Assign_Group", resourceCulture);
            }
        }
    }
}
