//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Config", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain      :.
        /// </summary>
        internal static string AD_Domain {
            get {
                return ResourceManager.GetString("AD_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string AD_Password {
            get {
                return ResourceManager.GetString("AD_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server ID :.
        /// </summary>
        internal static string AD_ServerId {
            get {
                return ResourceManager.GetString("AD_ServerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name :.
        /// </summary>
        internal static string AD_username {
            get {
                return ResourceManager.GetString("AD_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert !.
        /// </summary>
        internal static string AlertMsgModal_Header {
            get {
                return ResourceManager.GetString("AlertMsgModal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ALM_btnOK_Text {
            get {
                return ResourceManager.GetString("ALM_btnOK_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string btnTopBack_Text {
            get {
                return ResourceManager.GetString("btnTopBack_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database  :.
        /// </summary>
        internal static string DB_Database {
            get {
                return ResourceManager.GetString("DB_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPAddress :.
        /// </summary>
        internal static string DB_IPAdderess {
            get {
                return ResourceManager.GetString("DB_IPAdderess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string DB_Password {
            get {
                return ResourceManager.GetString("DB_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Number :.
        /// </summary>
        internal static string DB_Port {
            get {
                return ResourceManager.GetString("DB_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID :.
        /// </summary>
        internal static string DB_UserId {
            get {
                return ResourceManager.GetString("DB_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Type :.
        /// </summary>
        internal static string ESD_EmailType {
            get {
                return ResourceManager.GetString("ESD_EmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port :.
        /// </summary>
        internal static string ESD_Port {
            get {
                return ResourceManager.GetString("ESD_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string ESD_Pwd {
            get {
                return ResourceManager.GetString("ESD_Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply To Email :.
        /// </summary>
        internal static string ESD_ReplyEmail {
            get {
                return ResourceManager.GetString("ESD_ReplyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Name :.
        /// </summary>
        internal static string ESD_SenderName {
            get {
                return ResourceManager.GetString("ESD_SenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name :.
        /// </summary>
        internal static string ESD_ServerName {
            get {
                return ResourceManager.GetString("ESD_ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLS Enabled :.
        /// </summary>
        internal static string ESD_TlsEnabled {
            get {
                return ResourceManager.GetString("ESD_TlsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name :.
        /// </summary>
        internal static string ESD_UserName {
            get {
                return ResourceManager.GetString("ESD_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory Details.
        /// </summary>
        internal static string hd_ADDetails {
            get {
                return ResourceManager.GetString("hd_ADDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string hd_AD_Edit_Text {
            get {
                return ResourceManager.GetString("hd_AD_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Connection Details.
        /// </summary>
        internal static string hd_DBConnection {
            get {
                return ResourceManager.GetString("hd_DBConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string hd_DBC_Edit_Text {
            get {
                return ResourceManager.GetString("hd_DBC_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Server Details.
        /// </summary>
        internal static string hd_EmailServeDetails {
            get {
                return ResourceManager.GetString("hd_EmailServeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string hd_EmalSD_Edit_Text {
            get {
                return ResourceManager.GetString("hd_EmalSD_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Admin Info.
        /// </summary>
        internal static string hd_SAdmin {
            get {
                return ResourceManager.GetString("hd_SAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string hd_SAD_Edit_Text {
            get {
                return ResourceManager.GetString("hd_SAD_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string hd_SSD_Edit_Text {
            get {
                return ResourceManager.GetString("hd_SSD_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming Server Details.
        /// </summary>
        internal static string hd_StrServeDetails {
            get {
                return ResourceManager.GetString("hd_StrServeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOD Configuration Details.
        /// </summary>
        internal static string hd_VOD {
            get {
                return ResourceManager.GetString("hd_VOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string hd_VOD_Edit_Text {
            get {
                return ResourceManager.GetString("hd_VOD_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mdlAD_Cancel {
            get {
                return ResourceManager.GetString("mdlAD_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain&amp;nbsp;Name.
        /// </summary>
        internal static string mdlAD_Domain {
            get {
                return ResourceManager.GetString("mdlAD_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Domain Name.
        /// </summary>
        internal static string mdlAD_Domain_Need {
            get {
                return ResourceManager.GetString("mdlAD_Domain_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory Details.
        /// </summary>
        internal static string mdlAD_Header {
            get {
                return ResourceManager.GetString("mdlAD_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string mdlAD_Password {
            get {
                return ResourceManager.GetString("mdlAD_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Password.
        /// </summary>
        internal static string mdlAD_Password_need {
            get {
                return ResourceManager.GetString("mdlAD_Password_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string mdlAD_Save {
            get {
                return ResourceManager.GetString("mdlAD_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server&amp;nbsp;Id.
        /// </summary>
        internal static string mdlAD_ServerId {
            get {
                return ResourceManager.GetString("mdlAD_ServerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter ServerId.
        /// </summary>
        internal static string mdlAD_ServerId_need {
            get {
                return ResourceManager.GetString("mdlAD_ServerId_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Invalid Ip Address.
        /// </summary>
        internal static string mdlAD_ServerId_Valid {
            get {
                return ResourceManager.GetString("mdlAD_ServerId_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string mdlAD_UserName {
            get {
                return ResourceManager.GetString("mdlAD_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Username.
        /// </summary>
        internal static string mdlAD_Username_need {
            get {
                return ResourceManager.GetString("mdlAD_Username_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mdlDB_Cancel {
            get {
                return ResourceManager.GetString("mdlDB_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database&amp;nbsp;Name.
        /// </summary>
        internal static string mdlDB_DbName {
            get {
                return ResourceManager.GetString("mdlDB_DbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Database.
        /// </summary>
        internal static string mdlDB_DbName_Need {
            get {
                return ResourceManager.GetString("mdlDB_DbName_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Connection Details.
        /// </summary>
        internal static string mdlDB_Header {
            get {
                return ResourceManager.GetString("mdlDB_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip&amp;nbsp;Address.
        /// </summary>
        internal static string mdlDB_IPAddress {
            get {
                return ResourceManager.GetString("mdlDB_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter IP Address.
        /// </summary>
        internal static string mdlDB_IPAddress_Need {
            get {
                return ResourceManager.GetString("mdlDB_IPAddress_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Invalid Ip Address.
        /// </summary>
        internal static string mdlDB_IPAddress_Valid {
            get {
                return ResourceManager.GetString("mdlDB_IPAddress_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string mdlDB_password {
            get {
                return ResourceManager.GetString("mdlDB_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string mdlDB_Port {
            get {
                return ResourceManager.GetString("mdlDB_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Port.
        /// </summary>
        internal static string mdlDB_Port_Need {
            get {
                return ResourceManager.GetString("mdlDB_Port_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Invalid Port.
        /// </summary>
        internal static string mdlDB_Port_Valid {
            get {
                return ResourceManager.GetString("mdlDB_Port_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Password.
        /// </summary>
        internal static string mdlDB_Pwd_Need {
            get {
                return ResourceManager.GetString("mdlDB_Pwd_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string mdlDB_Save {
            get {
                return ResourceManager.GetString("mdlDB_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&amp;nbsp;Id.
        /// </summary>
        internal static string mdlDB_UserId {
            get {
                return ResourceManager.GetString("mdlDB_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter UserId.
        /// </summary>
        internal static string mdlDB_UserId_Need {
            get {
                return ResourceManager.GetString("mdlDB_UserId_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mdlEsD_Cancel {
            get {
                return ResourceManager.GetString("mdlEsD_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply To Email :.
        /// </summary>
        internal static string mdlESD_Email {
            get {
                return ResourceManager.GetString("mdlESD_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Type :.
        /// </summary>
        internal static string mdlESD_EmailType {
            get {
                return ResourceManager.GetString("mdlESD_EmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP.
        /// </summary>
        internal static string mdlESD_EmailType_Text {
            get {
                return ResourceManager.GetString("mdlESD_EmailType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP.
        /// </summary>
        internal static string mdlESD_EmailType_Value {
            get {
                return ResourceManager.GetString("mdlESD_EmailType_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email required.
        /// </summary>
        internal static string mdlESD_Email_need {
            get {
                return ResourceManager.GetString("mdlESD_Email_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter reply to eamil.
        /// </summary>
        internal static string mdlESD_Email_placeholder {
            get {
                return ResourceManager.GetString("mdlESD_Email_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter valid email.
        /// </summary>
        internal static string mdlESD_Email_valid {
            get {
                return ResourceManager.GetString("mdlESD_Email_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Server Details.
        /// </summary>
        internal static string mdlESD_Header {
            get {
                return ResourceManager.GetString("mdlESD_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name :.
        /// </summary>
        internal static string mdlESD_IPAddress {
            get {
                return ResourceManager.GetString("mdlESD_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server name required.
        /// </summary>
        internal static string mdlESD_IPAddress_Need {
            get {
                return ResourceManager.GetString("mdlESD_IPAddress_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter valid server name.
        /// </summary>
        internal static string mdlESD_IPAddress_Valid {
            get {
                return ResourceManager.GetString("mdlESD_IPAddress_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string mdlESD_password {
            get {
                return ResourceManager.GetString("mdlESD_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  required password.
        /// </summary>
        internal static string mdlESD_password_need {
            get {
                return ResourceManager.GetString("mdlESD_password_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port :.
        /// </summary>
        internal static string mdlESD_Port {
            get {
                return ResourceManager.GetString("mdlESD_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to required port.
        /// </summary>
        internal static string mdlESD_Port_Need {
            get {
                return ResourceManager.GetString("mdlESD_Port_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter port.
        /// </summary>
        internal static string mdlESD_Port_PlaceHolder {
            get {
                return ResourceManager.GetString("mdlESD_Port_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter valid port .
        /// </summary>
        internal static string mdlESD_Port_Valid {
            get {
                return ResourceManager.GetString("mdlESD_Port_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string mdlEsD_Save {
            get {
                return ResourceManager.GetString("mdlEsD_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Name :.
        /// </summary>
        internal static string mdlESD_Sender_name {
            get {
                return ResourceManager.GetString("mdlESD_Sender_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requried sender name.
        /// </summary>
        internal static string mdlESD_Sender_need {
            get {
                return ResourceManager.GetString("mdlESD_Sender_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter sender name.
        /// </summary>
        internal static string mdlESD_Sender_PlaceHolder {
            get {
                return ResourceManager.GetString("mdlESD_Sender_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter server name .
        /// </summary>
        internal static string mdlESD_servername_PlaceHolder {
            get {
                return ResourceManager.GetString("mdlESD_servername_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLS-Enabled :.
        /// </summary>
        internal static string mdlESD_TLS_Enabled {
            get {
                return ResourceManager.GetString("mdlESD_TLS_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name :.
        /// </summary>
        internal static string mdlESD_Username {
            get {
                return ResourceManager.GetString("mdlESD_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to required username.
        /// </summary>
        internal static string mdlESD_Username_need {
            get {
                return ResourceManager.GetString("mdlESD_Username_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter user name.
        /// </summary>
        internal static string mdlESD_Username_PlaceHolder {
            get {
                return ResourceManager.GetString("mdlESD_Username_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mdlSAD_Cancel {
            get {
                return ResourceManager.GetString("mdlSAD_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string mdlSAD_Email {
            get {
                return ResourceManager.GetString("mdlSAD_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Email.
        /// </summary>
        internal static string mdlSAD_Email_need {
            get {
                return ResourceManager.GetString("mdlSAD_Email_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Invalid Email Address.
        /// </summary>
        internal static string mdlSAD_Email_valid {
            get {
                return ResourceManager.GetString("mdlSAD_Email_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Admin Details.
        /// </summary>
        internal static string mdlSAD_Header {
            get {
                return ResourceManager.GetString("mdlSAD_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string mdlSAD_password {
            get {
                return ResourceManager.GetString("mdlSAD_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Password.
        /// </summary>
        internal static string mdlSAD_password_need {
            get {
                return ResourceManager.GetString("mdlSAD_password_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype&amp;nbsp;Password.
        /// </summary>
        internal static string mdlSAD_retyPwd {
            get {
                return ResourceManager.GetString("mdlSAD_retyPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Password.
        /// </summary>
        internal static string mdlSAD_retyPwd_need {
            get {
                return ResourceManager.GetString("mdlSAD_retyPwd_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Password Doesn&apos;t Match.
        /// </summary>
        internal static string mdlSAD_retyPwd_valid {
            get {
                return ResourceManager.GetString("mdlSAD_retyPwd_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string mdlSAD_Save {
            get {
                return ResourceManager.GetString("mdlSAD_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&amp;nbsp;Name.
        /// </summary>
        internal static string mdlSAD_Username {
            get {
                return ResourceManager.GetString("mdlSAD_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Username.
        /// </summary>
        internal static string mdlSAD_Username_need {
            get {
                return ResourceManager.GetString("mdlSAD_Username_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mdlSsD_Cancel {
            get {
                return ResourceManager.GetString("mdlSsD_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        internal static string mdlSSD_Email {
            get {
                return ResourceManager.GetString("mdlSSD_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stereaming Server Details.
        /// </summary>
        internal static string mdlSSD_Header {
            get {
                return ResourceManager.GetString("mdlSSD_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name :.
        /// </summary>
        internal static string mdlSsD_IPAddress {
            get {
                return ResourceManager.GetString("mdlSsD_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to required server name.
        /// </summary>
        internal static string mdlSsD_IPAddress_Need {
            get {
                return ResourceManager.GetString("mdlSsD_IPAddress_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter valid server name.
        /// </summary>
        internal static string mdlSsD_IPAddress_Valid {
            get {
                return ResourceManager.GetString("mdlSsD_IPAddress_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string mdlSSD_password {
            get {
                return ResourceManager.GetString("mdlSSD_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password required.
        /// </summary>
        internal static string mdlSSD_password_need {
            get {
                return ResourceManager.GetString("mdlSSD_password_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port :.
        /// </summary>
        internal static string mdlSsD_Port {
            get {
                return ResourceManager.GetString("mdlSsD_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to required port number.
        /// </summary>
        internal static string mdlSsD_Port_Need {
            get {
                return ResourceManager.GetString("mdlSsD_Port_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter port here.
        /// </summary>
        internal static string mdlSsD_Port_PlaceHolder {
            get {
                return ResourceManager.GetString("mdlSsD_Port_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter valid port number.
        /// </summary>
        internal static string mdlSsD_Port_Valid {
            get {
                return ResourceManager.GetString("mdlSsD_Port_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string mdlSsD_Save {
            get {
                return ResourceManager.GetString("mdlSsD_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter server name.
        /// </summary>
        internal static string mdlSsD_servername_PlaceHolder {
            get {
                return ResourceManager.GetString("mdlSsD_servername_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name  :.
        /// </summary>
        internal static string mdlSSD_Username {
            get {
                return ResourceManager.GetString("mdlSSD_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name required.
        /// </summary>
        internal static string mdlSsD_Username_need {
            get {
                return ResourceManager.GetString("mdlSsD_Username_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter user name.
        /// </summary>
        internal static string mdlSsD_Username_PlaceHolder {
            get {
                return ResourceManager.GetString("mdlSsD_Username_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive&amp;nbsp;Folder.
        /// </summary>
        internal static string mdlVOD_Archive {
            get {
                return ResourceManager.GetString("mdlVOD_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup&amp;nbsp;Folder.
        /// </summary>
        internal static string mdlVOD_BackUp {
            get {
                return ResourceManager.GetString("mdlVOD_BackUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Backup Folder.
        /// </summary>
        internal static string mdlVOD_BackUp_need {
            get {
                return ResourceManager.GetString("mdlVOD_BackUp_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mdlVOD_Cancel {
            get {
                return ResourceManager.GetString("mdlVOD_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination&amp;nbsp;Folder.
        /// </summary>
        internal static string mdlVOD_Dest {
            get {
                return ResourceManager.GetString("mdlVOD_Dest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Destination Folder.
        /// </summary>
        internal static string mdlVOD_Dest_need {
            get {
                return ResourceManager.GetString("mdlVOD_Dest_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOD Configuration Details.
        /// </summary>
        internal static string mdlVOD_Header {
            get {
                return ResourceManager.GetString("mdlVOD_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Archive Folder.
        /// </summary>
        internal static string mdlVOD_need {
            get {
                return ResourceManager.GetString("mdlVOD_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string mdlVOD_Save {
            get {
                return ResourceManager.GetString("mdlVOD_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Interval/Time.
        /// </summary>
        internal static string mdlVOD_SchdInterval {
            get {
                return ResourceManager.GetString("mdlVOD_SchdInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Or) Time.
        /// </summary>
        internal static string mdlVOD_SchdInterval_OrTime {
            get {
                return ResourceManager.GetString("mdlVOD_SchdInterval_OrTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simultanious&amp;nbsp;Video&amp;nbsp;&lt;br /&gt; Conversions.
        /// </summary>
        internal static string mdlVOD_Simul_Convertions {
            get {
                return ResourceManager.GetString("mdlVOD_Simul_Convertions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Select Video Conversion.
        /// </summary>
        internal static string mdlVOD_Simul_Convertions_Need {
            get {
                return ResourceManager.GetString("mdlVOD_Simul_Convertions_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sourcer&amp;nbsp;Folder.
        /// </summary>
        internal static string mdlVOD_SourceFolder {
            get {
                return ResourceManager.GetString("mdlVOD_SourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please Enter Source Folder.
        /// </summary>
        internal static string mdlVOD_SourceFolder_need {
            get {
                return ResourceManager.GetString("mdlVOD_SourceFolder_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming Email Details Not Saved.
        /// </summary>
        internal static string MSG_EmailServer_Save_Failed {
            get {
                return ResourceManager.GetString("MSG_EmailServer_Save_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Email Server Details Saved.
        /// </summary>
        internal static string MSG_EmailServer_Save_Sucess {
            get {
                return ResourceManager.GetString("MSG_EmailServer_Save_Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Streaming Server Details Saved.
        /// </summary>
        internal static string MSG_SteramingServer_Saved_Sucess {
            get {
                return ResourceManager.GetString("MSG_SteramingServer_Saved_Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming Server Details Not Saved.
        /// </summary>
        internal static string MSG_StreamingServer_Save_Failed {
            get {
                return ResourceManager.GetString("MSG_StreamingServer_Save_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email  :.
        /// </summary>
        internal static string SAD_Email {
            get {
                return ResourceManager.GetString("SAD_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string SAD_Pwd {
            get {
                return ResourceManager.GetString("SAD_Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name :.
        /// </summary>
        internal static string SAD_Username {
            get {
                return ResourceManager.GetString("SAD_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily at  {0}  once.
        /// </summary>
        internal static string SchedularIntervalFixedText {
            get {
                return ResourceManager.GetString("SchedularIntervalFixedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every  {0}  hours.
        /// </summary>
        internal static string SchedularIntervalRepeatText {
            get {
                return ResourceManager.GetString("SchedularIntervalRepeatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port  :.
        /// </summary>
        internal static string SSD_Port {
            get {
                return ResourceManager.GetString("SSD_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string SSD_Pwd {
            get {
                return ResourceManager.GetString("SSD_Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name :.
        /// </summary>
        internal static string SSD_StremServer {
            get {
                return ResourceManager.GetString("SSD_StremServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name :.
        /// </summary>
        internal static string SSD_UserName {
            get {
                return ResourceManager.GetString("SSD_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive     :.
        /// </summary>
        internal static string VOD_Archive {
            get {
                return ResourceManager.GetString("VOD_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Up     :.
        /// </summary>
        internal static string VOD_BackUp {
            get {
                return ResourceManager.GetString("VOD_BackUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination   :.
        /// </summary>
        internal static string VOD_Dest {
            get {
                return ResourceManager.GetString("VOD_Dest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval Time :.
        /// </summary>
        internal static string VOD_Interval {
            get {
                return ResourceManager.GetString("VOD_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Folder :.
        /// </summary>
        internal static string VOD_Source {
            get {
                return ResourceManager.GetString("VOD_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Conversion :.
        /// </summary>
        internal static string VOD_Videoconvertions {
            get {
                return ResourceManager.GetString("VOD_Videoconvertions", resourceCulture);
            }
        }
    }
}
