//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class District {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal District() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.District", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No District found.
        /// </summary>
        internal static string gvDist_EmtpyDataText {
            get {
                return ResourceManager.GetString("gvDist_EmtpyDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string gvDist_Hd_Actions {
            get {
                return ResourceManager.GetString("gvDist_Hd_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District Name.
        /// </summary>
        internal static string gvDist_Hd_DistName {
            get {
                return ResourceManager.GetString("gvDist_Hd_DistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create District.
        /// </summary>
        internal static string Head_Create_Dist {
            get {
                return ResourceManager.GetString("Head_Create_Dist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string Head_district {
            get {
                return ResourceManager.GetString("Head_district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert !.
        /// </summary>
        internal static string mdlAlrt_Head {
            get {
                return ResourceManager.GetString("mdlAlrt_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string mdlAlrt_Ok_btn {
            get {
                return ResourceManager.GetString("mdlAlrt_Ok_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mdlCD_Cancel_btn {
            get {
                return ResourceManager.GetString("mdlCD_Cancel_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District Name :.
        /// </summary>
        internal static string mdlCD_Dist_Name_Label {
            get {
                return ResourceManager.GetString("mdlCD_Dist_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter District Name here.
        /// </summary>
        internal static string mdlCD_Dist_Name_Placeholder {
            get {
                return ResourceManager.GetString("mdlCD_Dist_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create District.
        /// </summary>
        internal static string mdlCD_Hd_CreateDist {
            get {
                return ResourceManager.GetString("mdlCD_Hd_CreateDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string mdlCD_Save_btnText {
            get {
                return ResourceManager.GetString("mdlCD_Save_btnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mdlDel_cancel_btn {
            get {
                return ResourceManager.GetString("mdlDel_cancel_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are&amp;nbsp;you&amp;nbsp;sure&amp;nbsp;to&amp;nbsp;delete&amp;nbsp;district&amp;nbsp?.
        /// </summary>
        internal static string mdlDel_DelConfirm_Text {
            get {
                return ResourceManager.GetString("mdlDel_DelConfirm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string mdlDel_Delete_btn {
            get {
                return ResourceManager.GetString("mdlDel_Delete_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Warning.
        /// </summary>
        internal static string mdlDel_Head_Delwar {
            get {
                return ResourceManager.GetString("mdlDel_Head_Delwar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mdlUD_Cancel_text {
            get {
                return ResourceManager.GetString("mdlUD_Cancel_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District Name :.
        /// </summary>
        internal static string mdlUD_DistName_label {
            get {
                return ResourceManager.GetString("mdlUD_DistName_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter District Name here.
        /// </summary>
        internal static string mdlUD_DistName_placeHolder {
            get {
                return ResourceManager.GetString("mdlUD_DistName_placeHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit District.
        /// </summary>
        internal static string mdlUD_Head_EditDist {
            get {
                return ResourceManager.GetString("mdlUD_Head_EditDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string mdlUD_Save_text {
            get {
                return ResourceManager.GetString("mdlUD_Save_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District updated successfully.
        /// </summary>
        internal static string MSG_Distrct_Update_Sucess {
            get {
                return ResourceManager.GetString("MSG_Distrct_Update_Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District not deleted,as it is assigned to another user.
        /// </summary>
        internal static string MSG_District_Delete_Failed {
            get {
                return ResourceManager.GetString("MSG_District_Delete_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another object is depends on this District.
        /// </summary>
        internal static string MSG_District_Delete_Failed_Depends {
            get {
                return ResourceManager.GetString("MSG_District_Delete_Failed_Depends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District deleted successfully.
        /// </summary>
        internal static string MSG_District_Delete_Sucess {
            get {
                return ResourceManager.GetString("MSG_District_Delete_Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District saved sucessfully.
        /// </summary>
        internal static string MSG_District_Save_Sucess {
            get {
                return ResourceManager.GetString("MSG_District_Save_Sucess", resourceCulture);
            }
        }
    }
}
