//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MasterData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MasterData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MasterData", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Listing.
        /// </summary>
        internal static string chMa_Ad_Archive_Text {
            get {
                return ResourceManager.GetString("chMa_Ad_Archive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Management.
        /// </summary>
        internal static string chMa_Ad_GroupManage_Text {
            get {
                return ResourceManager.GetString("chMa_Ad_GroupManage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string chMa_Ad_Search_Text {
            get {
                return ResourceManager.GetString("chMa_Ad_Search_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string chMa_Ad_Usermange_Text {
            get {
                return ResourceManager.GetString("chMa_Ad_Usermange_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Management.
        /// </summary>
        internal static string chMa_Ad_VideoManage_Text {
            get {
                return ResourceManager.GetString("chMa_Ad_VideoManage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string chMa_User_Search_Text {
            get {
                return ResourceManager.GetString("chMa_User_Search_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Management.
        /// </summary>
        internal static string chMa_User_VideoManage_Text {
            get {
                return ResourceManager.GetString("chMa_User_VideoManage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string drp_Configuration_text {
            get {
                return ResourceManager.GetString("drp_Configuration_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string drp_LogOut_Text {
            get {
                return ResourceManager.GetString("drp_LogOut_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        internal static string hd_Arb_lnk_Text {
            get {
                return ResourceManager.GetString("hd_Arb_lnk_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string hd_Eng_lnk_Text {
            get {
                return ResourceManager.GetString("hd_Eng_lnk_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video on Demand.
        /// </summary>
        internal static string Hd_Title {
            get {
                return ResourceManager.GetString("Hd_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string logedUserWelcome_Text {
            get {
                return ResourceManager.GetString("logedUserWelcome_Text", resourceCulture);
            }
        }
    }
}
