//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Users {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Users() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Users", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnDeleteCancel_button {
            get {
                return ResourceManager.GetString("btnDeleteCancel_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnDeleteConform_button {
            get {
                return ResourceManager.GetString("btnDeleteConform_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string btnOk_button {
            get {
                return ResourceManager.GetString("btnOk_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string chkAll_checkbox {
            get {
                return ResourceManager.GetString("chkAll_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string chkSelectUser_checkbox {
            get {
                return ResourceManager.GetString("chkSelectUser_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group List.
        /// </summary>
        internal static string ddlGroupList_dropdown {
            get {
                return ResourceManager.GetString("ddlGroupList_dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups Edit.
        /// </summary>
        internal static string ddlGroupsEdit_dropdown {
            get {
                return ResourceManager.GetString("ddlGroupsEdit_dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups Filter.
        /// </summary>
        internal static string ddlGroupsFilter_dropdown {
            get {
                return ResourceManager.GetString("ddlGroupsFilter_dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string ddlGroups_label {
            get {
                return ResourceManager.GetString("ddlGroups_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        internal static string Domain_headertext {
            get {
                return ResourceManager.GetString("Domain_headertext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        internal static string FullName_headetext {
            get {
                return ResourceManager.GetString("FullName_headetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        internal static string GroupName_headertext {
            get {
                return ResourceManager.GetString("GroupName_headertext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string hd_UserManagement {
            get {
                return ResourceManager.GetString("hd_UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Color.
        /// </summary>
        internal static string hndRowBackColor_hiddenfield {
            get {
                return ResourceManager.GetString("hndRowBackColor_hiddenfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By.
        /// </summary>
        internal static string lblFilterBy {
            get {
                return ResourceManager.GetString("lblFilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string lblMessage_label {
            get {
                return ResourceManager.GetString("lblMessage_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string lblUserName_label {
            get {
                return ResourceManager.GetString("lblUserName_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Users to Group.
        /// </summary>
        internal static string lnkAssignUserstoGroup {
            get {
                return ResourceManager.GetString("lnkAssignUserstoGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string lnkDelete_link {
            get {
                return ResourceManager.GetString("lnkDelete_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string lnkEdit_link {
            get {
                return ResourceManager.GetString("lnkEdit_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        internal static string mdlAG_Assign {
            get {
                return ResourceManager.GetString("mdlAG_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Users to Group.
        /// </summary>
        internal static string mdlAG_AssingUsers {
            get {
                return ResourceManager.GetString("mdlAG_AssingUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mdlAG_Cancel {
            get {
                return ResourceManager.GetString("mdlAG_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Group.
        /// </summary>
        internal static string mdlAG_SelectGrp {
            get {
                return ResourceManager.GetString("mdlAG_SelectGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are&amp;nbsp;you&amp;nbsp;sure&amp;nbsp;to&amp;nbsp;delete&amp;nbsp;group&amp;nbsp;from&amp;nbsp;user ?.
        /// </summary>
        internal static string mdlDel_DelWarText {
            get {
                return ResourceManager.GetString("mdlDel_DelWarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Warning.
        /// </summary>
        internal static string mdlDel_Header {
            get {
                return ResourceManager.GetString("mdlDel_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        internal static string mdlEUP_Assign {
            get {
                return ResourceManager.GetString("mdlEUP_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mdlEUP_Cancel {
            get {
                return ResourceManager.GetString("mdlEUP_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify User Group.
        /// </summary>
        internal static string mdlEUP_ModfyGroup {
            get {
                return ResourceManager.GetString("mdlEUP_ModfyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Group.
        /// </summary>
        internal static string mdlEUP_SelectGroup {
            get {
                return ResourceManager.GetString("mdlEUP_SelectGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string mdlEUP_UserName {
            get {
                return ResourceManager.GetString("mdlEUP_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID.
        /// </summary>
        internal static string UserID_headertext {
            get {
                return ResourceManager.GetString("UserID_headertext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string UserName_headertext {
            get {
                return ResourceManager.GetString("UserName_headertext", resourceCulture);
            }
        }
    }
}
