//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VideoManagement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VideoManagement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.VideoManagement", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert !.
        /// </summary>
        internal static string AlertMsgModal_Header {
            get {
                return ResourceManager.GetString("AlertMsgModal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ALM_btnOK_Text {
            get {
                return ResourceManager.GetString("ALM_btnOK_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ALM_lblMessage_Text {
            get {
                return ResourceManager.GetString("ALM_lblMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tags Details.
        /// </summary>
        internal static string EditTags_Header {
            get {
                return ResourceManager.GetString("EditTags_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ETM_btnCancelTag_Text {
            get {
                return ResourceManager.GetString("ETM_btnCancelTag_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ETM_btnSaveTag_Text {
            get {
                return ResourceManager.GetString("ETM_btnSaveTag_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video&amp;nbsp;Name :.
        /// </summary>
        internal static string ETM_lblVideoNameText {
            get {
                return ResourceManager.GetString("ETM_lblVideoNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community&amp;nbsp;Tags :.
        /// </summary>
        internal static string ETM_txtCommunityTagText {
            get {
                return ResourceManager.GetString("ETM_txtCommunityTagText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District Tags :.
        /// </summary>
        internal static string ETM_txtDistrictTagText {
            get {
                return ResourceManager.GetString("ETM_txtDistrictTagText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Tags :.
        /// </summary>
        internal static string ETM_txtRoadTagText {
            get {
                return ResourceManager.GetString("ETM_txtRoadTagText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Name : .
        /// </summary>
        internal static string ETM_VideoName {
            get {
                return ResourceManager.GetString("ETM_VideoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string grd_Hd_Edit {
            get {
                return ResourceManager.GetString("grd_Hd_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string grd_Hd_Play {
            get {
                return ResourceManager.GetString("grd_Hd_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string grd_Hd_Status {
            get {
                return ResourceManager.GetString("grd_Hd_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAG.
        /// </summary>
        internal static string grd_Hd_Tag {
            get {
                return ResourceManager.GetString("grd_Hd_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Name.
        /// </summary>
        internal static string grd_Hd_VideoName {
            get {
                return ResourceManager.GetString("grd_Hd_VideoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Videos to Group.
        /// </summary>
        internal static string GroupSelectModal_Header {
            get {
                return ResourceManager.GetString("GroupSelectModal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        internal static string GSM_btnAssign_Text {
            get {
                return ResourceManager.GetString("GSM_btnAssign_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string GSM_btnCancel_Text {
            get {
                return ResourceManager.GetString("GSM_btnCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select&amp;nbsp;Group.
        /// </summary>
        internal static string GSM_ddlGroupListText {
            get {
                return ResourceManager.GetString("GSM_ddlGroupListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Management.
        /// </summary>
        internal static string HDRVideoManagement {
            get {
                return ResourceManager.GetString("HDRVideoManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By.
        /// </summary>
        internal static string lblFilterBy {
            get {
                return ResourceManager.GetString("lblFilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Videos to Group.
        /// </summary>
        internal static string lnkAssignVideostoGroup {
            get {
                return ResourceManager.GetString("lnkAssignVideostoGroup", resourceCulture);
            }
        }
    }
}
